### ISSUE TITLE
Doesn't work error

### ISSUE THREAD

**Issue by adammxiv** [DedInc/DemoDisabler#1]
i didn't find mods folder so i made one and added the folder and did run minecraft through forge and it doesn't work. it still says demo.. is there any way i can fix it
![image](https://github.com/user-attachments/assets/9c854a16-02c1-4c5a-a0a8-6f6cd2495ca6)

**Comment by idkwhyihave5accounts** [comment]
It does work with 1.16.5, I tested it  and the batch has an instance of 1.16.5

**Comment by DedInc** [comment]
> i didn't find mods folder so i made one and added the folder and did run minecraft through forge and it doesn't work. it still says demo.. is there any way i can fix it ![image](https://private-user-images.githubusercontent.com/179339779/361168446-9c854a16-02c1-4c5a-a0a8-6f6cd2495ca6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODcxNzQsIm5iZiI6MTcyNTU4Njg3NCwicGF0aCI6Ii8xNzkzMzk3NzkvMzYxMTY4NDQ2LTljODU0YTE2LTAyYzEtNGM1YS1hMGE4LTZmNmNkMjQ5NWNhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwMTQxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTM2YjRiMjUxMzQ3NWYwYjcyYjY2N2NjMDQ5YWIzMjI1ZDkyMjFkMjRmNjhmZGMzYWVlNWZhYjcyYjQxNGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3bYU5lMIgC5NXZrAmJrWp6xCusHEVXietjfLQLCVA8M)

only for 1.16.5

if u want for this version write me on telegram @maehdak_van

**Comment by Jimhasaburger** [comment]
> > i didn't find mods folder so i made one and added the folder and did run minecraft through forge and it doesn't work. it still says demo.. is there any way i can fix it ![image](https://private-user-images.githubusercontent.com/179339779/361168446-9c854a16-02c1-4c5a-a0a8-6f6cd2495ca6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODcxNzQsIm5iZiI6MTcyNTU4Njg3NCwicGF0aCI6Ii8xNzkzMzk3NzkvMzYxMTY4NDQ2LTljODU0YTE2LTAyYzEtNGM1YS1hMGE4LTZmNmNkMjQ5NWNhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwMTQxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTM2YjRiMjUxMzQ3NWYwYjcyYjY2N2NjMDQ5YWIzMjI1ZDkyMjFkMjRmNjhmZGMzYWVlNWZhYjcyYjQxNGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3bYU5lMIgC5NXZrAmJrWp6xCusHEVXietjfLQLCVA8M)
> 
> only for 1.16.5
> 
> if u want for this version write me on telegram @maehdak_van

NO ONE USES TELEGRAM AND IF THEY DO THEIR PERSONAL IMFORMATION HAS BEEN STOLEN
